"""Typos

Revision ID: 0086965dcd77
Revises: 1c882a52d3ad
Create Date: 2021-01-07 00:56:14.057506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0086965dcd77'
down_revision = '1c882a52d3ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gear_settings', sa.Column('ringSize', sa.String(length=10), nullable=True))
    op.add_column('gear_settings', sa.Column('sightHole', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gear_settings', 'sightHole')
    op.drop_column('gear_settings', 'ringSize')
    # ### end Alembic commands ###
