"""setting columns are now JSON

Revision ID: 0a751b33def5
Revises: 102549ef9190
Create Date: 2021-02-23 12:55:51.146614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a751b33def5'
down_revision = '102549ef9190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage', sa.Column('settings', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('settings_300m', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('settings_400m', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('settings_500m', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('settings_600m', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('settings_700m', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('settings_800m', sa.JSON(), nullable=True))
    op.drop_column('user', 'dist_300m')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dist_300m', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('user', 'settings_800m')
    op.drop_column('user', 'settings_700m')
    op.drop_column('user', 'settings_600m')
    op.drop_column('user', 'settings_500m')
    op.drop_column('user', 'settings_400m')
    op.drop_column('user', 'settings_300m')
    op.drop_column('stage', 'settings')
    # ### end Alembic commands ###
