"""JSON column test

Revision ID: 102549ef9190
Revises: aaf3c91fb021
Create Date: 2021-02-23 12:35:14.376403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102549ef9190'
down_revision = 'aaf3c91fb021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dist_300m', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'dist_300m')
    # ### end Alembic commands ###
