"""removed unique emails

Revision ID: 13963740a120
Revises: b0fdfb240308
Create Date: 2020-12-29 16:00:36.693736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13963740a120'
down_revision = 'b0fdfb240308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
