"""school col

Revision ID: 189e741e616d
Revises: aeb78b6c1c57
Create Date: 2020-12-09 10:26:58.574182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189e741e616d'
down_revision = 'aeb78b6c1c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('school', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'school')
    # ### end Alembic commands ###
