"""Added a Gear Settings Table

Revision ID: 1c882a52d3ad
Revises: dfb9894fea72
Create Date: 2021-01-07 00:51:33.783498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c882a52d3ad'
down_revision = 'dfb9894fea72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gear_settings',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('jacket', sa.String(length=10), nullable=True),
    sa.Column('glove', sa.String(length=10), nullable=True),
    sa.Column('hat', sa.String(length=10), nullable=True),
    sa.Column('slingHole', sa.String(length=10), nullable=True),
    sa.Column('slingPoint', sa.String(length=10), nullable=True),
    sa.Column('butOut', sa.String(length=10), nullable=True),
    sa.Column('butUp', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gear_settings')
    # ### end Alembic commands ###
