"""added Elevation Settings

Revision ID: 207edf4704d9
Revises: 6c3e8847ef73
Create Date: 2021-01-13 19:07:02.450219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207edf4704d9'
down_revision = '6c3e8847ef73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ADI300m', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('ADI400m', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('ADI500m', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('ADI500y', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('ADI600m', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('ADI600y', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('ADI700m', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('ADI800m', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('Fore300m', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('Fore400m', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('Fore500m', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('Fore500y', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('Fore600m', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('Fore600y', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('Fore700m', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('Fore800m', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('PPU300m', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('PPU400m', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('PPU500m', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('PPU500y', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('PPU600m', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('PPU600y', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('PPU700m', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('PPU800m', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'PPU800m')
    op.drop_column('user', 'PPU700m')
    op.drop_column('user', 'PPU600y')
    op.drop_column('user', 'PPU600m')
    op.drop_column('user', 'PPU500y')
    op.drop_column('user', 'PPU500m')
    op.drop_column('user', 'PPU400m')
    op.drop_column('user', 'PPU300m')
    op.drop_column('user', 'Fore800m')
    op.drop_column('user', 'Fore700m')
    op.drop_column('user', 'Fore600y')
    op.drop_column('user', 'Fore600m')
    op.drop_column('user', 'Fore500y')
    op.drop_column('user', 'Fore500m')
    op.drop_column('user', 'Fore400m')
    op.drop_column('user', 'Fore300m')
    op.drop_column('user', 'ADI800m')
    op.drop_column('user', 'ADI700m')
    op.drop_column('user', 'ADI600y')
    op.drop_column('user', 'ADI600m')
    op.drop_column('user', 'ADI500y')
    op.drop_column('user', 'ADI500m')
    op.drop_column('user', 'ADI400m')
    op.drop_column('user', 'ADI300m')
    # ### end Alembic commands ###
