"""new models

Revision ID: 2568bfc4c1fc
Revises: 99024dd8c3ed
Create Date: 2021-01-06 12:30:45.214084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2568bfc4c1fc'
down_revision = '99024dd8c3ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stage',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('duration', sa.DateTime(), nullable=True),
    sa.Column('groupSize', sa.Float(), nullable=True),
    sa.Column('rangeDistance', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_duration'), 'stage', ['duration'], unique=False)
    op.create_table('shot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stageID', sa.BigInteger(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('xPos', sa.Float(), nullable=True),
    sa.Column('yPos', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['stageID'], ['stage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shot_timestamp'), 'shot', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shot_timestamp'), table_name='shot')
    op.drop_table('shot')
    op.drop_index(op.f('ix_stage_duration'), table_name='stage')
    op.drop_table('stage')
    # ### end Alembic commands ###
