"""Added gear Settings to user table

Revision ID: 29a01e54034d
Revises: dfb9894fea72
Create Date: 2021-01-07 09:46:19.862189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a01e54034d'
down_revision = 'dfb9894fea72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('butOut', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('butUp', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('glove', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('hat', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('jacket', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('ringSize', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('sightHole', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('slingHole', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('slingPoint', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'slingPoint')
    op.drop_column('user', 'slingHole')
    op.drop_column('user', 'sightHole')
    op.drop_column('user', 'ringSize')
    op.drop_column('user', 'jacket')
    op.drop_column('user', 'hat')
    op.drop_column('user', 'glove')
    op.drop_column('user', 'butUp')
    op.drop_column('user', 'butOut')
    # ### end Alembic commands ###
