"""added coaches

Revision ID: 46a623838607
Revises: 0bb083a28cee
Create Date: 2021-02-12 10:13:30.329525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a623838607'
down_revision = '0bb083a28cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isCoach', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isCoach')
    # ### end Alembic commands ###
