"""reference update

Revision ID: 569dd0b4e8bc
Revises: d3c58bdc5190
Create Date: 2022-08-31 16:22:01.064734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569dd0b4e8bc'
down_revision = 'd3c58bdc5190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('club_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'club', ['club_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'club_id')
    # ### end Alembic commands ###
