"""fixed typos in Shot table

Revision ID: 6c2276cca2d1
Revises: 2568bfc4c1fc
Create Date: 2021-01-06 12:39:37.691431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c2276cca2d1'
down_revision = '2568bfc4c1fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shot', sa.Column('numV', sa.Integer(), nullable=True))
    op.add_column('shot', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('shot', sa.Column('sighter', sa.Boolean(), nullable=True))
    op.add_column('stage', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_stage_timestamp'), 'stage', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stage_timestamp'), table_name='stage')
    op.drop_column('stage', 'timestamp')
    op.drop_column('shot', 'sighter')
    op.drop_column('shot', 'score')
    op.drop_column('shot', 'numV')
    # ### end Alembic commands ###
