"""users table

Revision ID: 6c3e8847ef73
Revises: 29a01e54034d
Create Date: 2021-01-10 23:50:26.569098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3e8847ef73'
down_revision = '29a01e54034d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dob', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('mobile', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('permitType', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('rifleSerial', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('sharing', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sharing')
    op.drop_column('user', 'rifleSerial')
    op.drop_column('user', 'permitType')
    op.drop_column('user', 'mobile')
    op.drop_column('user', 'dob')
    # ### end Alembic commands ###
