"""restructure

Revision ID: 6f8897ac6e8b
Revises: e2791d1e2077
Create Date: 2020-12-05 22:22:59.473694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f8897ac6e8b'
down_revision = 'e2791d1e2077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('fName', sa.String(length=70), nullable=True),
    sa.Column('sName', sa.String(length=70), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('schoolID', sa.String(length=20), nullable=True),
    sa.Column('schoolYr', sa.String(length=2), nullable=True),
    sa.Column('shooterID', sa.String(length=20), nullable=True),
    sa.Column('permitNumber', sa.String(length=20), nullable=True),
    sa.Column('permitExpiry', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jsonFilename', sa.String(length=128), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.DateTime(), nullable=True),
    sa.Column('groupSize', sa.Float(), nullable=True),
    sa.Column('rangeType', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_duration'), 'stage', ['duration'], unique=False)
    op.create_index(op.f('ix_stage_timestamp'), 'stage', ['timestamp'], unique=False)
    op.create_table('shot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stageID', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('xPos', sa.Float(), nullable=True),
    sa.Column('yPos', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['stageID'], ['stage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shot_timestamp'), 'shot', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shot_timestamp'), table_name='shot')
    op.drop_table('shot')
    op.drop_index(op.f('ix_stage_timestamp'), table_name='stage')
    op.drop_index(op.f('ix_stage_duration'), table_name='stage')
    op.drop_table('stage')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
