"""empty message

Revision ID: 79295366c24d
Revises: 50bbe0accd3c
Create Date: 2021-05-23 15:28:06.691637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '79295366c24d'
down_revision = '50bbe0accd3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('elevation_300m', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('elevation_400m', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('elevation_500m', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('elevation_600m', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('elevation_700m', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('elevation_800m', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('ringSize_300m', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('ringSize_400m', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('ringSize_500m', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('ringSize_600m', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('ringSize_700m', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('ringSize_800m', sa.String(length=20), nullable=True))
    op.drop_column('user', 'settings_700m')
    op.drop_column('user', 'settings_400m')
    op.drop_column('user', 'settings_300m')
    op.drop_column('user', 'settings_500m')
    op.drop_column('user', 'settings_800m')
    op.drop_column('user', 'settings_600m')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('settings_600m', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('settings_800m', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('settings_500m', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('settings_300m', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('settings_400m', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('settings_700m', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('user', 'ringSize_800m')
    op.drop_column('user', 'ringSize_700m')
    op.drop_column('user', 'ringSize_600m')
    op.drop_column('user', 'ringSize_500m')
    op.drop_column('user', 'ringSize_400m')
    op.drop_column('user', 'ringSize_300m')
    op.drop_column('user', 'elevation_800m')
    op.drop_column('user', 'elevation_700m')
    op.drop_column('user', 'elevation_600m')
    op.drop_column('user', 'elevation_500m')
    op.drop_column('user', 'elevation_400m')
    op.drop_column('user', 'elevation_300m')
    # ### end Alembic commands ###
