"""reset

Revision ID: 99024dd8c3ed
Revises: f45f194cf466
Create Date: 2021-01-06 12:24:34.964229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99024dd8c3ed'
down_revision = 'f45f194cf466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shot')
    op.drop_table('stage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_stage_timestamp', 'stage', ['timestamp'], unique=False)
    # ### end Alembic commands ###
