"""access levels

Revision ID: aaf3c91fb021
Revises: 46a623838607
Create Date: 2021-02-12 10:18:49.935534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf3c91fb021'
down_revision = '46a623838607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access', sa.Integer(), nullable=True))
    op.drop_column('user', 'isAdmin')
    op.drop_column('user', 'isCoach')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isCoach', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('isAdmin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'access')
    # ### end Alembic commands ###
