"""added isAdmin

Revision ID: aeb78b6c1c57
Revises: 6f8897ac6e8b
Create Date: 2020-12-07 12:08:33.483049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb78b6c1c57'
down_revision = '6f8897ac6e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isAdmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isAdmin')
    # ### end Alembic commands ###
