"""isActive

Revision ID: b0fdfb240308
Revises: 189e741e616d
Create Date: 2020-12-23 09:19:35.394571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0fdfb240308'
down_revision = '189e741e616d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isActive', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('lastActive', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lastActive')
    op.drop_column('user', 'isActive')
    # ### end Alembic commands ###
