"""group Center

Revision ID: b1bc79f2725c
Revises: 207edf4704d9
Create Date: 2021-02-03 21:55:13.073597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1bc79f2725c'
down_revision = '207edf4704d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage', sa.Column('groupX', sa.Float(), nullable=True))
    op.add_column('stage', sa.Column('groupY', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stage', 'groupY')
    op.drop_column('stage', 'groupX')
    # ### end Alembic commands ###
