"""distance changed to integer

Revision ID: c77aa8b18fe7
Revises: 0a751b33def5
Create Date: 2021-02-23 20:11:09.212715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77aa8b18fe7'
down_revision = '0a751b33def5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage', sa.Column('distance', sa.VARCHAR(length=10), nullable=True))
    op.drop_column('stage', 'rangeDistance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage', sa.Column('rangeDistance', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('stage', 'distance')
    # ### end Alembic commands ###
