"""renaming tables

Revision ID: d3c58bdc5190
Revises: 1529bbb206b1
Create Date: 2022-08-31 16:18:01.311807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd3c58bdc5190'
down_revision = '1529bbb206b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email_setting', sa.Integer(), nullable=True),
    sa.Column('season_start', sa.DateTime(), nullable=True),
    sa.Column('season_end', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('settings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email_setting', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('season_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('season_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='settings_pkey')
    )
    op.drop_table('club')
    # ### end Alembic commands ###
