"""reference update

Revision ID: d73e242af571
Revises: 569dd0b4e8bc
Create Date: 2022-08-31 16:22:47.631301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd73e242af571'
down_revision = '569dd0b4e8bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('clubID', sa.Integer(), nullable=True))
    op.drop_constraint('user_club_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'club', ['clubID'], ['id'])
    op.drop_column('user', 'club_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('club_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_club_id_fkey', 'user', 'club', ['club_id'], ['id'])
    op.drop_column('user', 'clubID')
    # ### end Alembic commands ###
