"""changed numV to vScore

Revision ID: d97e7d1fdcfc
Revises: c77aa8b18fe7
Create Date: 2021-02-26 13:42:09.688418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97e7d1fdcfc'
down_revision = 'c77aa8b18fe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shot', sa.Column('vScore', sa.Integer(), nullable=True))
    op.drop_column('shot', 'numV')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shot', sa.Column('numV', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('shot', 'vScore')
    # ### end Alembic commands ###
