"""remove duration column

Revision ID: dfb9894fea72
Revises: 6c2276cca2d1
Create Date: 2021-01-06 14:27:16.523538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dfb9894fea72'
down_revision = '6c2276cca2d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stage_duration', table_name='stage')
    op.drop_column('stage', 'duration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage', sa.Column('duration', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_stage_duration', 'stage', ['duration'], unique=False)
    # ### end Alembic commands ###
