"""Shot Table

Revision ID: e2791d1e2077
Revises: 11e81d490062
Create Date: 2020-12-05 18:39:44.230357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2791d1e2077'
down_revision = '11e81d490062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print("yes")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shot')
    op.drop_table('stage')
    op.drop_table('user')
    # ### end Alembic commands ###
