"""Updated shot table

Revision ID: f45f194cf466
Revises: 13963740a120
Create Date: 2021-01-05 14:30:54.622779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f45f194cf466'
down_revision = '13963740a120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage', sa.Column('jsonID', sa.String(length=128), nullable=True))
    op.add_column('stage', sa.Column('rangeDistance', sa.String(length=10), nullable=True))
    op.drop_column('stage', 'rangeType')
    op.drop_column('stage', 'jsonFilename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage', sa.Column('jsonFilename', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('stage', sa.Column('rangeType', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('stage', 'rangeDistance')
    op.drop_column('stage', 'jsonID')
    # ### end Alembic commands ###
